export const {
  HOME,
  REGISTER,
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  CHANGE_PASSWORD,
  CHANGE_EMAIL,
  CONFIRM_EMAIL,
  CHECK_EMAIL,
  TERMS_AND_CONDITIONS,
  PRIVACY_POLICY,
  NEWS,
  CONTACT,
  SELL,
  TUTORIALS,
  ABOUT,
  FAQ,
} = {
  HOME: '/',
  REGISTER: '/register',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot_password',
  RESET_PASSWORD: '/reset_password',
  CHANGE_PASSWORD: '/change_password',
  CHANGE_EMAIL: '/change_email',
  CONFIRM_EMAIL: '/register/confirm_email',
  CHECK_EMAIL: '/register/check_email',
  TERMS_AND_CONDITIONS: '/terms_and_conditions',
  PRIVACY_POLICY: '/privacy_policy',
  NEWS: '/news',
  CONTACT: '/contact',
  SELL: '/sell',
  TUTORIALS: '/tutorials',
  ABOUT: '/about',
  FAQ: '/faq',
} as const;
