export const {
  DASHBOARD,
  SUPPLIERS_PRODUCTS,
  ORDERS,
  PRICE,
  ANALYTICS,
  FEEDBACK,
  ACCOUNT_SETUP_PERSONAL_INFO,
  ACCOUNT_SETUP_BUSINESS_INFO,
  ADD_PRODUCT,
} = {
  DASHBOARD: '/dashboard',
  SUPPLIERS_PRODUCTS: '/products_list',
  ORDERS: '/orders',
  PRICE: '/price',
  ANALYTICS: '/analytics',
  FEEDBACK: '/feedback',
  ACCOUNT_SETUP_PERSONAL_INFO: '/account_setup_personal_info',
  ACCOUNT_SETUP_BUSINESS_INFO: '/account_setup_business_info',
  ADD_PRODUCT: '/add_product',
} as const;
