export {
  HOME,
  ABOUT,
  FAQ,
  NEWS,
  CONTACT,
  SELL,
  TUTORIALS,
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  CHANGE_PASSWORD,
  CHANGE_EMAIL,
  CONFIRM_EMAIL,
  CHECK_EMAIL,
  TERMS_AND_CONDITIONS,
  REGISTER,
  PRIVACY_POLICY,
  PRODUCTS_LIST,
} from './constans/root';

export {
  ORDER_HISTORY_DETAILS,
  PRODUCT_DETAILS,
  ORDER_HISTORY,
  CART,
  CHECKOUT,
  CHECKOUT_SUCCESS,
  HELP,
  FAVORITES,
  PERSONAL_ACCOUNT,
} from './constans/seller';

export {
  ADD_PRODUCT,
  ACCOUNT_SETUP_BUSINESS_INFO,
  ACCOUNT_SETUP_PERSONAL_INFO,
  ANALYTICS,
  ORDERS,
  PRICE,
  DASHBOARD,
  FEEDBACK,
} from './constans/supplier';
