export { MainPage } from '../general-pages/index';
export { CartPage } from './CartPage/CartPage';
export { ProductPage } from './ProductPage/ProductPage';
export { SellerProfilePage } from 'pages/seller-pages/SellerProfilePage/SellerProfilePage';
export { SellerFavoritesList } from './SellerFavoritesList/SellerFavoritesList';
export { OrderDetailsPage } from './OrderDetailsPage/OrderDetailsPage';
export { OrderHistoryPage } from './OrderHistoryPage/OrderHistoryPage';
export { CheckoutPage } from './CheckoutPage/CheckoutPage';
export { CheckoutSuccessPage } from './CheckoutSuccessPage/CheckoutSuccessPage';
