version: "3.9"

services:
  nginx:
    image: nginx:latest
    build: 
      context: ${PWD}
      dockerfile: docker/Dockerfile.nginx
    command: /bin/bash -c \
      "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
      nginx -g 'daemon off;'"
    env_file:
      - ${PWD}/.env
    depends_on:
      - web
    ports:
      - ${EXPOSE_PORT}:${EXPOSE_PORT}
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
