version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run frontend' && \
      yarn start"
    ports:
      - ${EXPOSE_PORT}:${EXPOSE_PORT}
    expose:
      - ${EXPOSE_PORT}
    env_file:
      - ${PWD}/.env
    restart: unless-stopped
