 import iconImg from '../../../../../assets/img/icons/icon-img.png'
 const backgroundImg = {
    'display': 'flex',
    'flexDirection': 'column',
    'alignItems': 'center',
    'justifyContent': 'center',
    'height': '40px',
    'width': '40px',
    'backgroundColor': 'var(--back)',
    'borderRadius': '50%'
  }

  const styleImg = {
    'width': '40%'
  }
 
 const products = [
    {
        id: 1,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 2,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 3,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 4,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 5,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 6,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 7,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 8,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 9,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 10,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 11,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 12,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 13,
        SKU : '00000025',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'On Sale',
        price: '$8.50/pc',
        balaceUnits: '2500',
        visibility: 'Visible',
    },
    {
        id: 14,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 15,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 16,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 17,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 18,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 19,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 20,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 21,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 22,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 23,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 24,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 25,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 26,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 27,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 28,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 29,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 30,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 31,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 32,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 33,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 34,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    },
    {
        id: 35,
        SKU : '00000017',
        picture: <div style={backgroundImg}><img src={iconImg} alt="img" style={styleImg}/></div>,
        name: 'Hot Sale Winter Casual Dresses Drawstring Sweet Hooded Dress Fall Clothes',
        creationDate: '07.17.2022 9:14 ам',
        status: 'Off-sale',
        price: '$8.50/pc',
        balaceUnits: '1700',
        visibility: 'Hidden',
    }
];

const fetchAll = () =>
    new Promise((resolve) => {
        window.setTimeout(function () {
            resolve(products);
        }, 1000);
    });

export default {
    fetchAll
};
